/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Paneles_principales;

import Paneles_rotativos.Inventario;
import Paneles_rotativos.Venta;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author lautaro
 */


public class Principal extends javax.swing.JFrame {
    
    Inventario inventario;
    Venta venta;
            
    /**
     * Creates new form Principal
     */
    public Principal(){
        try {
            this.inventario = new Inventario();
            this.venta = new Venta();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        
        
        MostrarPanel(inventario);
        boton_inventario.setFont(new java.awt.Font("Segoe UI Black", 0, 12));
    }
    
    public void MostrarPanel(JPanel p) {

        p.setLocation(0, 0);
        contenido.removeAll();
        contenido.add(p);
        contenido.revalidate();
        contenido.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        boton_inventario = new javax.swing.JLabel();
        boton_presupuestos = new javax.swing.JLabel();
        boton_usuarios = new javax.swing.JLabel();
        boton_caja = new javax.swing.JLabel();
        boton_venta = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(214, 226, 195));

        boton_inventario.setForeground(new java.awt.Color(0, 46, 15));
        boton_inventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boton_inventario.setText("INVENTARIO");
        boton_inventario.setToolTipText("");
        boton_inventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton_inventarioMousePressed(evt);
            }
        });

        boton_presupuestos.setForeground(new java.awt.Color(0, 46, 15));
        boton_presupuestos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boton_presupuestos.setText("PRESUPUESTOS");

        boton_usuarios.setForeground(new java.awt.Color(0, 46, 15));
        boton_usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boton_usuarios.setText("USUARIOS");

        boton_caja.setForeground(new java.awt.Color(0, 46, 15));
        boton_caja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boton_caja.setText("CAJA");

        boton_venta.setForeground(new java.awt.Color(0, 46, 15));
        boton_venta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boton_venta.setText("VENTA");
        boton_venta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton_ventaMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boton_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boton_presupuestos, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
            .addComponent(boton_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boton_caja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boton_venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(boton_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_presupuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_caja, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(333, Short.MAX_VALUE))
        );

        contenido.setMinimumSize(new java.awt.Dimension(900, 600));
        contenido.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_inventarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_inventarioMousePressed
        MostrarPanel(inventario);
        try {
            inventario.tablaproductos ();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        boton_inventario.setBackground(new java.awt.Color(0, 204, 145));
        boton_inventario.setFont(new java.awt.Font("Segoe UI Black", 0, 12));
        boton_presupuestos.setFont(new java.awt.Font("Segoe UI ", 0, 12));
        boton_caja.setFont(new java.awt.Font("Segoe UI ", 0, 12));
        boton_usuarios.setFont(new java.awt.Font("Segoe UI ", 0, 12));
        boton_venta.setFont(new java.awt.Font("Segoe UI ", 0, 12));
    }//GEN-LAST:event_boton_inventarioMousePressed

    private void boton_ventaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ventaMousePressed
        MostrarPanel(venta);
        boton_venta.setBackground(new java.awt.Color(0, 204, 145));
        boton_venta.setFont(new java.awt.Font("Segoe UI Black", 0, 12));
        boton_presupuestos.setFont(new java.awt.Font("Segoe UI ", 0, 12));
        boton_caja.setFont(new java.awt.Font("Segoe UI ", 0, 12));
        boton_usuarios.setFont(new java.awt.Font("Segoe UI ", 0, 12));
        boton_inventario.setFont(new java.awt.Font("Segoe UI ", 0, 12));
    }//GEN-LAST:event_boton_ventaMousePressed
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boton_caja;
    private javax.swing.JLabel boton_inventario;
    private javax.swing.JLabel boton_presupuestos;
    private javax.swing.JLabel boton_usuarios;
    private javax.swing.JLabel boton_venta;
    private javax.swing.JPanel contenido;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
