/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Paneles_principales;

import Paneles_rotativos.Inventario;
import Paneles_rotativos.Usuario;
import Paneles_rotativos.Venta;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author lautaro
 */


public class Principal extends javax.swing.JFrame {
    
    Inventario inventario;
    Venta venta;
    Usuario usua;
            
    /**
     * Creates new form Principal
     */
    public Principal(){
        try {
            this.inventario = new Inventario();
            this.venta = new Venta();
            this.usua = new Usuario ();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        
        
        MostrarPanel(inventario);
        boton_inventario.setFont(new java.awt.Font("Segoe UI Black", 0, 12));
    }
    
    public void MostrarPanel(JPanel p) {

        p.setLocation(0, 0);
        contenido.removeAll();
        contenido.add(p);
        contenido.revalidate();
        contenido.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        boton_inventario = new javax.swing.JLabel();
        boton_usuarios = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();
        boton_venta = new javax.swing.JLabel();
        boton_caja1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(214, 226, 195));

        boton_inventario.setForeground(new java.awt.Color(0, 46, 15));
        boton_inventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boton_inventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/baseline_assignment_black_24dp.png"))); // NOI18N
        boton_inventario.setText("INVENTARIO");
        boton_inventario.setToolTipText("");
        boton_inventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton_inventarioMousePressed(evt);
            }
        });

        boton_usuarios.setForeground(new java.awt.Color(0, 46, 15));
        boton_usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boton_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/baseline_account_circle_black_24dp_1.png"))); // NOI18N
        boton_usuarios.setText("USUARIO");
        boton_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton_usuariosMousePressed(evt);
            }
        });

        salir.setForeground(new java.awt.Color(0, 46, 15));
        salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salir.setText("SALIR");
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salirMousePressed(evt);
            }
        });

        boton_venta.setForeground(new java.awt.Color(0, 46, 15));
        boton_venta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boton_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/baseline_attach_money_black_24dp.png"))); // NOI18N
        boton_venta.setText("VENTA");
        boton_venta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton_venta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boton_ventaMousePressed(evt);
            }
        });

        boton_caja1.setForeground(new java.awt.Color(0, 46, 15));
        boton_caja1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boton_caja1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/kisspng-cash-register-computer-icons-money-payment-point-o-5af3897e79ef57.5804234915259098864995 (1).png"))); // NOI18N
        boton_caja1.setText("CAJA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boton_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(boton_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
            .addComponent(salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton_caja1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_venta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boton_inventario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_caja1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 331, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        contenido.setMinimumSize(new java.awt.Dimension(900, 600));
        contenido.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 1014, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_inventarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_inventarioMousePressed
        MostrarPanel(inventario);
        try {
            inventario.tablaproductos ();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        boton_inventario.setBackground(new java.awt.Color(0, 204, 145));
        boton_inventario.setFont(new java.awt.Font("Segoe UI Black", 0, 12));
        //boton_presupuestos.setFont(new java.awt.Font("Segoe UI ", 0, 12));
        salir.setFont(new java.awt.Font("Segoe UI ", 0, 12));
        boton_usuarios.setFont(new java.awt.Font("Segoe UI ", 0, 12));
        boton_venta.setFont(new java.awt.Font("Segoe UI ", 0, 12));
    }//GEN-LAST:event_boton_inventarioMousePressed

    private void boton_ventaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_ventaMousePressed
        MostrarPanel(venta);
        boton_venta.setBackground(new java.awt.Color(0, 204, 145));
        boton_venta.setFont(new java.awt.Font("Segoe UI Black", 0, 12));
       // boton_presupuestos.setFont(new java.awt.Font("Segoe UI ", 0, 12));
        salir.setFont(new java.awt.Font("Segoe UI ", 0, 12));
        boton_usuarios.setFont(new java.awt.Font("Segoe UI ", 0, 12));
        boton_inventario.setFont(new java.awt.Font("Segoe UI ", 0, 12));
    }//GEN-LAST:event_boton_ventaMousePressed

    private void salirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMousePressed
        System.exit(0);
    }//GEN-LAST:event_salirMousePressed

    private void boton_usuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_usuariosMousePressed
        MostrarPanel(usua);
        boton_usuarios.setBackground(new java.awt.Color(0, 204, 145));
        boton_usuarios.setFont(new java.awt.Font("Segoe UI Black", 0, 12));
       // boton_presupuestos.setFont(new java.awt.Font("Segoe UI ", 0, 12));
        salir.setFont(new java.awt.Font("Segoe UI ", 0, 12));
        boton_venta.setFont(new java.awt.Font("Segoe UI ", 0, 12));
        boton_inventario.setFont(new java.awt.Font("Segoe UI ", 0, 12));
    }//GEN-LAST:event_boton_usuariosMousePressed
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boton_caja1;
    private javax.swing.JLabel boton_inventario;
    private javax.swing.JLabel boton_usuarios;
    private javax.swing.JLabel boton_venta;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel salir;
    // End of variables declaration//GEN-END:variables
}
